import type { Category, Ingredient, Dish, Order } from "./types";

export const categories: Category[] = [
  { id: 'CAT001', name: 'BREAKFAST EGG', description: '' },
  { id: 'CAT002', name: 'BREAKFAST PROTEIN RICH FOOD', description: '' },
  { id: 'CAT003', name: 'LUNCH PROTEIN RICH FOOD (Light)', description: '' },
  { id: 'CAT004', name: 'SUPPER PROTEIN RICH FOOD (Main)', description: '' },
  { id: 'CAT005', name: 'BREAD AND ROLLS', description: '' },
  { id: 'CAT006', name: 'RUSKS and BISCUITS', description: '' },
  { id: 'CAT007', name: 'CONFECTIONARY', description: '' },
  { id: 'CAT008', name: 'MILK PRODUCTS', description: '' },
  { id: 'CAT009', name: 'DAIRY PRODUCTS_CHEESE', description: '' },
  { id: 'CAT010', name: 'DAIRY PRODUCTS_YOGHURT', description: '' },
  { id: 'CAT011', name: 'DAIRY PRODUCTS_EVAP', description: '' },
  { id: 'CAT012', name: 'DAIRY PRODUCTS_ICECREAM', description: '' },
  { id: 'CAT013', name: 'FATS', description: '' },
  { id: 'CAT014', name: 'SUGAR', description: '' },
  { id: 'CAT015', name: 'PORRIDGES', description: '' },
  { id: 'CAT016', name: 'CEREALS', description: '' },
  { id: 'CAT017', name: 'STARCH', description: '' },
  { id: 'CAT018', name: 'VEGETABLES FRESH, FROZEN, PRE-PREPARED', description: '' },
  { id: 'CAT019', name: 'FRESH FRUIT IN SEASON', description: '' },
  { id: 'CAT020', name: 'JAMS and SPREADS', description: '' },
  { id: 'CAT021', name: 'BEVERAGES', description: '' },
  { id: 'CAT022', name: 'FRUIT JUICE', description: '' },
  { id: 'CAT023', name: 'DINNING ROOM COMMODITIES', description: '' },
  { id: 'CAT024', name: 'KITCHEN COMMODITIES and GENERAL ITEMS', description: '' },
  { id: 'CAT025', name: 'HERBS AND SPICES', description: '' },
  { id: 'CAT026', name: 'JELLY POWDERS AND DESSERTS', description: '' },
  { id: 'CAT027', name: 'SOUP POWDER', description: '' },
  { id: 'CAT028', name: 'DESSERT SAUCES', description: '' },
  { id: 'CAT029', name: 'SAUCES&GRAVIES', description: '' },
  { id: 'CAT030', name: 'SUPPLEMENTARY ITEMS', description: '' },
  { id: 'CAT031', name: 'Spreads and Fillings', description: '' },
];

export const ingredients: Ingredient[] = [
  { id: 'P001', name: 'Eggs Large Fresh (B)', categoryId: 'CAT001', unitOfMeasure: 'ea', packagingSize: '30', stock: 0 },
  { id: 'P002', name: 'Eggs Large Fresh (B) (VEG)', categoryId: 'CAT001', unitOfMeasure: 'ea', packagingSize: '90', stock: 0 },
  { id: 'P003', name: 'Bacon Sliced Middle (B)', categoryId: 'CAT002', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P004', name: 'Bacon Sliced Shoulder (B)', categoryId: 'CAT002', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P005', name: 'Bacon Sliced Streaky (B)', categoryId: 'CAT002', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P006', name: 'Bean Salad (Sous Bone) (VEG) (B)', categoryId: 'CAT002', unitOfMeasure: 'lt', packagingSize: '5', stock: 0 },
  { id: 'P007', name: 'Beans Butter Dry (VEG) (B)', categoryId: 'CAT002', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P008', name: 'Beef Ground Mince (B)', categoryId: 'CAT002', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P009', name: 'Boerewors (B)', categoryId: 'CAT002', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P010', name: 'Canned Beans In Tomato Sauce (B)', categoryId: 'CAT002', unitOfMeasure: 'g', packagingSize: '410', stock: 0 },
  { id: 'P011', name: 'Canned Beans In Tomato Sauce (VEG) (B)', categoryId: 'CAT002', unitOfMeasure: 'g', packagingSize: '410', stock: 0 },
  { id: 'P012', name: 'Canned Pilchards (B)', categoryId: 'CAT002', unitOfMeasure: 'g', packagingSize: '410', stock: 0 },
  { id: 'P013', name: 'Cheese Cheddar (VEG) (B)', categoryId: 'CAT002', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P014', name: 'Cheese Gouda (VEG) (B)', categoryId: 'CAT002', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P015', name: 'Cheese Mozzarella (VEG) (B)', categoryId: 'CAT002', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P016', name: 'Chicken Bacon (B)', categoryId: 'CAT002', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P017', name: 'Chicken Liver (B)', categoryId: 'CAT002', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P018', name: 'Chicken Nuggets (B)', categoryId: 'CAT002', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P019', name: 'Chicken Russian (B)', categoryId: 'CAT002', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P020', name: 'Chicken Vienna (B)', categoryId: 'CAT002', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P021', name: 'Chicken Wors (B)', categoryId: 'CAT002', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P022', name: 'Cottage Pie Vegetarian Frozen (VEG) (B)', categoryId: 'CAT002', unitOfMeasure: 'ea', packagingSize: '24', stock: 0 },
  { id: 'P023', name: 'Crisp Louisiana Tenders Frozen (VEG) (B)', categoryId: 'CAT002', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P024', name: 'Fish Cakes (B)', categoryId: 'CAT002', unitOfMeasure: 'kg', packagingSize: '5', stock: 0 },
  { id: 'P025', name: 'Fish Fingers Frozen (B)', categoryId: 'CAT002', unitOfMeasure: 'kg', packagingSize: '5', stock: 0 },
  { id: 'P026', name: 'Lentils Brown Dry (VEG) (B)', categoryId: 'CAT002', unitOfMeasure: 'g', packagingSize: '500', stock: 0 },
  { id: 'P027', name: 'Mutton Sausage (B)', categoryId: 'CAT002', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P028', name: 'Nuggets Chicken Style Frozen (VEG) (B)', categoryId: 'CAT002', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P029', name: 'Pies Vegetarian Frozen (VEG) (B)', categoryId: 'CAT002', unitOfMeasure: 'ea', packagingSize: '24', stock: 0 },
  { id: 'P030', name: 'Sausage Country Style (B)', categoryId: 'CAT002', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P031', name: 'Sausage Russian (B)', categoryId: 'CAT002', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P032', name: 'Slicing Polony Frozen (VEG) (B)', categoryId: 'CAT002', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P033', name: 'Snitzels Golden Crumbed (VEG) (B)', categoryId: 'CAT002', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P034', name: 'Soya Mince Dry (VEG) (B)', categoryId: 'CAT002', unitOfMeasure: 'g', packagingSize: '500', stock: 0 },
  { id: 'P035', name: 'Soya Mince Frozen (VEG) (B)', categoryId: 'CAT002', unitOfMeasure: 'g', packagingSize: '500', stock: 0 },
  { id: 'P036', name: 'Soya Strips Frozen (VEG) (B)', categoryId: 'CAT002', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P037', name: 'Split Peas Dry (VEG) (B)', categoryId: 'CAT002', unitOfMeasure: 'g', packagingSize: '500', stock: 0 },
  { id: 'P038', name: 'Vegetarian Burgers (B)', categoryId: 'CAT002', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P039', name: 'Vegetarian Sausages (B)', categoryId: 'CAT002', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P040', name: 'Vienna Smoked (B)', categoryId: 'CAT002', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P041', name: 'Bean Salad (Sous Bone) (VEG) (LM)', categoryId: 'CAT003', unitOfMeasure: 'lt', packagingSize: '20', stock: 0 },
  { id: 'P042', name: 'Beans Butter Dry (VEG) (LM)', categoryId: 'CAT003', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P043', name: 'Beef Ground Mince (LM)', categoryId: 'CAT003', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P044', name: 'Beef Snitzel (LM)', categoryId: 'CAT003', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P045', name: 'Beef Steak Tenderised Steak portions (Topside) (LM)', categoryId: 'CAT003', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P046', name: 'Beef Stir-fry (LM)', categoryId: 'CAT003', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P047', name: 'Boerewors (LM)', categoryId: 'CAT003', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P048', name: 'Braai packs (3 meats 550g) (LM)', categoryId: 'CAT003', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P049', name: 'Burgers Frozen (VEG) (LM)', categoryId: 'CAT003', unitOfMeasure: 'g', packagingSize: '1', stock: 0 },
  { id: 'P050', name: 'Canned Beans In Tomato Sauce (VEG) (LM)', categoryId: 'CAT003', unitOfMeasure: 'g', packagingSize: '410', stock: 0 },
  { id: 'P051', name: 'Canned Pilchards (LM)', categoryId: 'CAT003', unitOfMeasure: 'g', packagingSize: '410', stock: 0 },
  { id: 'P052', name: 'Canned Tuna Solid in Brine (LM)', categoryId: 'CAT003', unitOfMeasure: 'g', packagingSize: '170', stock: 0 },
  { id: 'P053', name: 'Chicken Breasts Fillet (LM)', categoryId: 'CAT003', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P054', name: 'Chicken Cubed (LM)', categoryId: 'CAT003', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P055', name: 'Chicken Feet (LM)', categoryId: 'CAT003', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P056', name: 'Chicken Loaf Chilled (LM)', categoryId: 'CAT003', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P057', name: 'Chicken Mince (LM)', categoryId: 'CAT003', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P058', name: 'Chicken Patties (LM)', categoryId: 'CAT003', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P059', name: 'Chicken Sausage (LM)', categoryId: 'CAT003', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P060', name: 'Chicken Snitzel 125G (LM)', categoryId: 'CAT003', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P061', name: 'Chicken Steaklets 120G (LM)', categoryId: 'CAT003', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P062', name: 'Chicken Thighs Portions (LM)', categoryId: 'CAT003', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P063', name: 'Chicken Vienna (LM)', categoryId: 'CAT003', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P064', name: 'Cottage Pie Vegetarian Frozen (VEG) (LM)', categoryId: 'CAT003', unitOfMeasure: 'ea', packagingSize: '24', stock: 0 },
  { id: 'P065', name: 'Crisp Louisiana Tenders Frozen (VEG) (LM)', categoryId: 'CAT003', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P066', name: 'Fish Cakes Frozen (LM)', categoryId: 'CAT003', unitOfMeasure: 'kg', packagingSize: '5', stock: 0 },
  { id: 'P067', name: 'Fish Hake Fillets (LM)', categoryId: 'CAT003', unitOfMeasure: 'kg', packagingSize: '5', stock: 0 },
  { id: 'P068', name: 'Fish Snoek Mildly Cured (LM)', categoryId: 'CAT003', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P069', name: 'Fish Tuna Steaks (LM)', categoryId: 'CAT003', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P070', name: 'Ham Cooked Chilled (LM)', categoryId: 'CAT003', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P071', name: 'Lentils Brown Dry (VEG) (LM)', categoryId: 'CAT003', unitOfMeasure: 'g', packagingSize: '500', stock: 0 },
  { id: 'P072', name: 'Loaf Salami Chilled (LM)', categoryId: 'CAT003', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P073', name: 'Nuggets Chicken Style Frozen (VEG) (LM)', categoryId: 'CAT003', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P074', name: 'Patties Ground Beef Mince (LM)', categoryId: 'CAT003', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P075', name: 'Pepper Loaf Chilled (LM)', categoryId: 'CAT003', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P076', name: 'Pie Beef and Onion Frozen (200g) (LM)', categoryId: 'CAT003', unitOfMeasure: 'ea', packagingSize: '24', stock: 0 },
  { id: 'P077', name: 'Pie Cheese and Mushroom Frozen (200g) (LM)', categoryId: 'CAT003', unitOfMeasure: 'ea', packagingSize: '24', stock: 0 },
  { id: 'P078', name: 'Pie Chicken and Mushroom Frozen (200g) (LM)', categoryId: 'CAT003', unitOfMeasure: 'ea', packagingSize: '24', stock: 0 },
  { id: 'P079', name: 'Pie Pepper Steak Frozen (200g) (LM)', categoryId: 'CAT003', unitOfMeasure: 'ea', packagingSize: '24', stock: 0 },
  { id: 'P080', name: 'Pie Sausage Roll Beef(200g) (LM)', categoryId: 'CAT003', unitOfMeasure: 'ea', packagingSize: '24', stock: 0 },
  { id: 'P081', name: 'Pie Sausage Roll Chicken(200g) (LM)', categoryId: 'CAT003', unitOfMeasure: 'ea', packagingSize: '24', stock: 0 },
  { id: 'P082', name: 'Pies Vegetarian Frozen (VEG) (LM)', categoryId: 'CAT003', unitOfMeasure: 'ea', packagingSize: '24', stock: 0 },
  { id: 'P083', name: 'Polony French Chilled (LM)', categoryId: 'CAT003', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P084', name: 'Pork Neck Steak (LM)', categoryId: 'CAT003', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P085', name: 'Sausage Russian (LM)', categoryId: 'CAT003', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P086', name: 'Sausages Country Style (LM)', categoryId: 'CAT003', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P087', name: 'Sausages Frozen (VEG) (LM)', categoryId: 'CAT003', unitOfMeasure: 'g', packagingSize: '500', stock: 0 },
  { id: 'P088', name: 'Sausages Vienna Smoked Chilled (LM)', categoryId: 'CAT003', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P089', name: 'Slicing Polony Frozen (VEG) (LM)', categoryId: 'CAT003', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P090', name: 'Snitzels Golden Crumbed (VEG) (LM)', categoryId: 'CAT003', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P091', name: 'Soya Mince Dry (VEG) (LM)', categoryId: 'CAT003', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P092', name: 'Soya Mince Frozen (VEG) (LM)', categoryId: 'CAT003', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P093', name: 'Soya Strips Frozen (VEG) (LM)', categoryId: 'CAT003', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P094', name: 'Split Peas Dry (VEG) (LM)', categoryId: 'CAT003', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P095', name: 'Bean Salad (Sous Bone) (VEG) (MM)', categoryId: 'CAT004', unitOfMeasure: 'lt', packagingSize: '5', stock: 0 },
  { id: 'P096', name: 'Beans Butter Dry (VEG) (MM)', categoryId: 'CAT004', unitOfMeasure: 'g', packagingSize: '500', stock: 0 },
  { id: 'P097', name: 'Beef Brisket (MM)', categoryId: 'CAT004', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P098', name: 'Beef Chuck (MM)', categoryId: 'CAT004', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P099', name: 'Beef Club Steak (MM)', categoryId: 'CAT004', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P100', name: 'Beef Diced (MM)', categoryId: 'CAT004', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P101', name: 'Beef Ground Mince (MM)', categoryId: 'CAT004', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P102', name: 'Beef Liver (MM)', categoryId: 'CAT004', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P103', name: 'Beef Mogodu (MM)', categoryId: 'CAT004', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P104', name: 'Beef Oxtail (MM)', categoryId: 'CAT004', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P105', name: 'Beef Rump Steak (MM)', categoryId: 'CAT004', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P106', name: 'Beef Scotch Fillet Steak (MM)', categoryId: 'CAT004', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P107', name: 'Beef Silverside (MM)', categoryId: 'CAT004', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P108', name: 'Beef Sirloin (MM)', categoryId: 'CAT004', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P109', name: 'Beef Snitzel (MM)', categoryId: 'CAT004', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P110', name: 'Beef Thick Flank (MM)', categoryId: 'CAT004', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P111', name: 'Beef Topside (MM)', categoryId: 'CAT004', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P112', name: 'Braai packs (3 meats 550g) (MM)', categoryId: 'CAT004', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P113', name: 'Burgers Frozen (VEG) (MM)', categoryId: 'CAT004', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P114', name: 'Canned Beans In Tomato Sauce (VEG) (MM)', categoryId: 'CAT004', unitOfMeasure: 'g', packagingSize: '410', stock: 0 },
  { id: 'P115', name: 'Chicken Breast Fillets (MM)', categoryId: 'CAT004', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P116', name: 'Chicken Breast Portions (MM)', categoryId: 'CAT004', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P117', name: 'Chicken Leg Quarters (175g) (MM)', categoryId: 'CAT004', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P118', name: 'Chicken Mince (MM)', categoryId: 'CAT004', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P119', name: 'Chicken Patties (MM)', categoryId: 'CAT004', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P120', name: 'Chicken Snitzel 125G (MM)', categoryId: 'CAT004', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P121', name: 'Chicken Steaklets 100G (MM)', categoryId: 'CAT004', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P122', name: 'Chicken Thighs Portions (MM)', categoryId: 'CAT004', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P123', name: 'Chicken Whole Baby (MM)', categoryId: 'CAT004', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P124', name: 'Chicken Wors (MM)', categoryId: 'CAT004', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P125', name: 'Cottage Pie Vegetarian Frozen (VEG) (MM)', categoryId: 'CAT004', unitOfMeasure: 'ea', packagingSize: '24', stock: 0 },
  { id: 'P126', name: 'Crisp Louisiana Tenders Frozen (VEG) (MM)', categoryId: 'CAT004', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P127', name: 'Eisbein (MM)', categoryId: 'CAT004', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P128', name: 'Hake Fillets Frozen (MM)', categoryId: 'CAT004', unitOfMeasure: 'kg', packagingSize: '5', stock: 0 },
  { id: 'P129', name: 'Lentils Brown Dry (VEG) (MM)', categoryId: 'CAT004', unitOfMeasure: 'g', packagingSize: '500', stock: 0 },
  { id: 'P130', name: 'Mutton Leg (MM)', categoryId: 'CAT004', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P131', name: 'Mutton Loin Chops (MM)', categoryId: 'CAT004', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P132', name: 'Mutton Mogodu (MM)', categoryId: 'CAT004', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P133', name: 'Mutton Ribs (MM)', categoryId: 'CAT004', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P134', name: 'Mutton Shoulder Chops (MM)', categoryId: 'CAT004', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P135', name: 'Mutton Stewing with bone (MM)', categoryId: 'CAT004', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P136', name: 'Mutton Stewing without bone (MM)', categoryId: 'CAT004', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P137', name: 'Nuggets Chicken Style Frozen (VEG) (MM)', categoryId: 'CAT004', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P138', name: 'Pies Vegetarian Frozen (VEG) (MM)', categoryId: 'CAT004', unitOfMeasure: 'ea', packagingSize: '24', stock: 0 },
  { id: 'P139', name: 'Pork Leg (MM)', categoryId: 'CAT004', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P140', name: 'Pork Loin Chops (MM)', categoryId: 'CAT004', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P141', name: 'Pork Neck Steak (MM)', categoryId: 'CAT004', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P142', name: 'Pork Ribs (MM)', categoryId: 'CAT004', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P143', name: 'Sausage Russian (MM)', categoryId: 'CAT004', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P144', name: 'Sausage Russian Chicken (MM)', categoryId: 'CAT004', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P145', name: 'Sausages Country Style (MM)', categoryId: 'CAT004', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P146', name: 'Sausages Frozen (VEG) (MM)', categoryId: 'CAT004', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P147', name: 'Sausages Vienna Smoked Chilled (MM)', categoryId: 'CAT004', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P148', name: 'Slicing Polony Frozen (VEG) (MM)', categoryId: 'CAT004', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P149', name: 'Snitzels Golden Crumbed (VEG) (MM)', categoryId: 'CAT004', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P150', name: 'Soya Mince Dry (VEG) (MM)', categoryId: 'CAT004', unitOfMeasure: 'g', packagingSize: '500', stock: 0 },
  { id: 'P151', name: 'Soya Mince Frozen (VEG) (MM)', categoryId: 'CAT004', unitOfMeasure: 'g', packagingSize: '500', stock: 0 },
  { id: 'P152', name: 'Soya Strips Frozen (VEG) (MM)', categoryId: 'CAT004', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P153', name: 'Split Peas Dry (VEG) (MM)', categoryId: 'CAT004', unitOfMeasure: 'g', packagingSize: '500', stock: 0 },
  { id: 'P154', name: 'Bread Brown', categoryId: 'CAT005', unitOfMeasure: 'g', packagingSize: '700', stock: 0 },
  { id: 'P155', name: 'Bread Brown Low GI', categoryId: 'CAT005', unitOfMeasure: 'g', packagingSize: '800', stock: 0 },
  { id: 'P156', name: 'Bread Crusted Wheat', categoryId: 'CAT005', unitOfMeasure: 'g', packagingSize: '700', stock: 0 },
  { id: 'P157', name: 'Bread Seed Loaf', categoryId: 'CAT005', unitOfMeasure: 'g', packagingSize: '700', stock: 0 },
  { id: 'P158', name: 'Bread White', categoryId: 'CAT005', unitOfMeasure: 'g', packagingSize: '700', stock: 0 },
  { id: 'P159', name: 'Bread Whole Wheat', categoryId: 'CAT005', unitOfMeasure: 'g', packagingSize: '700', stock: 0 },
  { id: 'P160', name: 'Buns Bread Fresh Garlic', categoryId: 'CAT005', unitOfMeasure: 'ea', packagingSize: '9', stock: 0 },
  { id: 'P161', name: 'Buns Bread White Fresh (65g)', categoryId: 'CAT005', unitOfMeasure: 'ea', packagingSize: '6', stock: 0 },
  { id: 'P162', name: 'Buns Bread White Fresh Cheese', categoryId: 'CAT005', unitOfMeasure: 'ea', packagingSize: '4', stock: 0 },
  { id: 'P163', name: 'Buns Bread Whole Wheat Fresh (65g)', categoryId: 'CAT005', unitOfMeasure: 'ea', packagingSize: '6', stock: 0 },
  { id: 'P164', name: 'Muffin Bran (75g)', categoryId: 'CAT005', unitOfMeasure: 'ea', packagingSize: '4', stock: 0 },
  { id: 'P165', name: 'Pita (65g)', categoryId: 'CAT005', unitOfMeasure: 'ea', packagingSize: '6', stock: 0 },
  { id: 'P166', name: 'Rolls Bread White Fresh (65g)', categoryId: 'CAT005', unitOfMeasure: 'ea', packagingSize: '6', stock: 0 },
  { id: 'P167', name: 'Rolls Bread Whole Wheat Fresh (65g)', categoryId: 'CAT005', unitOfMeasure: 'ea', packagingSize: '6', stock: 0 },
  { id: 'P168', name: 'Wrap Tortilla Brown (70g)', categoryId: 'CAT005', unitOfMeasure: 'ea', packagingSize: '6', stock: 0 },
  { id: 'P169', name: 'Assorted Biscuits', categoryId: 'CAT006', unitOfMeasure: 'g', packagingSize: '200', stock: 0 },
  { id: 'P170', name: 'Crackers Cream', categoryId: 'CAT006', unitOfMeasure: 'g', packagingSize: '200', stock: 0 },
  { id: 'P171', name: 'Crackers Wheat (PROVITA)', categoryId: 'CAT006', unitOfMeasure: 'g', packagingSize: '250', stock: 0 },
  { id: 'P172', name: 'Ginger Nut Biscuits', categoryId: 'CAT006', unitOfMeasure: 'g', packagingSize: '200', stock: 0 },
  { id: 'P173', name: 'Individually Wrapped Mixed Biscuits (9g)', categoryId: 'CAT006', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P174', name: 'Lemon Creams', categoryId: 'CAT006', unitOfMeasure: 'g', packagingSize: '200', stock: 0 },
  { id: 'P175', name: 'Marie Biscuit', categoryId: 'CAT006', unitOfMeasure: 'g', packagingSize: '200', stock: 0 },
  { id: 'P176', name: 'Romany Creams', categoryId: 'CAT006', unitOfMeasure: 'g', packagingSize: '200', stock: 0 },
  { id: 'P177', name: 'Rusks Buttermilk', categoryId: 'CAT006', unitOfMeasure: 'g', packagingSize: '500', stock: 0 },
  { id: 'P178', name: 'Rusks Plain', categoryId: 'CAT006', unitOfMeasure: 'g', packagingSize: '500', stock: 0 },
  { id: 'P179', name: 'Tennis Biscuit', categoryId: 'CAT006', unitOfMeasure: 'g', packagingSize: '200', stock: 0 },
  { id: 'P180', name: '10', categoryId: 'CAT007', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P181', name: '11', categoryId: 'CAT007', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P182', name: '12', categoryId: 'CAT007', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P183', name: '13', categoryId: 'CAT007', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P184', name: '14', categoryId: 'CAT007', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P185', name: '15', categoryId: 'CAT007', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P186', name: '16', categoryId: 'CAT007', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P187', name: '17', categoryId: 'CAT007', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P188', name: '18', categoryId: 'CAT007', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P189', name: '19', categoryId: 'CAT007', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P190', name: '20', categoryId: 'CAT007', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P191', name: '21', categoryId: 'CAT007', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P192', name: '22', categoryId: 'CAT007', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P193', name: '23', categoryId: 'CAT007', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P194', name: '24', categoryId: 'CAT007', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P195', name: '25', categoryId: 'CAT007', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P196', name: '26', categoryId: 'CAT007', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P197', name: '27', categoryId: 'CAT007', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P198', name: '28', categoryId: 'CAT007', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P199', name: '29', categoryId: 'CAT007', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P200', name: '30', categoryId: 'CAT007', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P201', name: '31', categoryId: 'CAT007', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P202', name: '32', categoryId: 'CAT007', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P203', name: '33', categoryId: 'CAT007', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P204', name: '34', categoryId: 'CAT007', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P205', name: '35', categoryId: 'CAT007', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P206', name: '36', categoryId: 'CAT007', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P207', name: '37', categoryId: 'CAT007', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P208', name: '38', categoryId: 'CAT007', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P209', name: '39', categoryId: 'CAT007', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P210', name: '40', categoryId: 'CAT007', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P211', name: 'Scone homemade', categoryId: 'CAT007', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P212', name: 'Scone Pre-made', categoryId: 'CAT007', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P213', name: 'Maas', categoryId: 'CAT008', unitOfMeasure: 'ml', packagingSize: '500', stock: 0 },
  { id: 'P214', name: 'Milk Fresh', categoryId: 'CAT008', unitOfMeasure: 'lt', packagingSize: '4', stock: 0 },
  { id: 'P215', name: 'Milk Fresh Cartons', categoryId: 'CAT008', unitOfMeasure: 'lt', packagingSize: '4', stock: 0 },
  { id: 'P216', name: 'Milk Fresh Low Fat', categoryId: 'CAT008', unitOfMeasure: 'lt', packagingSize: '2', stock: 0 },
  { id: 'P217', name: 'Milk Fresh Plastic Bottles', categoryId: 'CAT008', unitOfMeasure: 'ml', packagingSize: '500', stock: 0 },
  { id: 'P218', name: 'Milk Long Life', categoryId: 'CAT008', unitOfMeasure: 'lt', packagingSize: '6', stock: 0 },
  { id: 'P219', name: 'Milk Skim', categoryId: 'CAT008', unitOfMeasure: 'ml', packagingSize: '8', stock: 0 },
  { id: 'P220', name: 'Cheese Cheddar', categoryId: 'CAT009', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P221', name: 'Cheese Feta', categoryId: 'CAT009', unitOfMeasure: 'g', packagingSize: '400', stock: 0 },
  { id: 'P222', name: 'Cheese Gouda', categoryId: 'CAT009', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P223', name: 'Cheese Mozzarella', categoryId: 'CAT009', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P224', name: 'Cheese Tussers', categoryId: 'CAT009', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P225', name: 'Portions Cheese Gouda (15G)', categoryId: 'CAT009', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P226', name: 'Yoghurt Apricot', categoryId: 'CAT010', unitOfMeasure: 'g', packagingSize: '375', stock: 0 },
  { id: 'P227', name: 'Yoghurt Assorted', categoryId: 'CAT010', unitOfMeasure: 'g', packagingSize: '175', stock: 0 },
  { id: 'P228', name: 'Yoghurt Assorted Low Fat', categoryId: 'CAT010', unitOfMeasure: 'g', packagingSize: '175', stock: 0 },
  { id: 'P229', name: 'Yoghurt Bulgarian (VEG)', categoryId: 'CAT010', unitOfMeasure: 'g', packagingSize: '175', stock: 0 },
  { id: 'P230', name: 'Yoghurt Cape Fruit', categoryId: 'CAT010', unitOfMeasure: 'g', packagingSize: '175', stock: 0 },
  { id: 'P231', name: 'Yoghurt Chocolate', categoryId: 'CAT010', unitOfMeasure: 'g', packagingSize: '175', stock: 0 },
  { id: 'P232', name: 'Yoghurt Custard', categoryId: 'CAT010', unitOfMeasure: 'g', packagingSize: '175', stock: 0 },
  { id: 'P233', name: 'Yoghurt Full Cream (VEG)', categoryId: 'CAT010', unitOfMeasure: 'g', packagingSize: '175', stock: 0 },
  { id: 'P234', name: 'Yoghurt Granadilla', categoryId: 'CAT010', unitOfMeasure: 'g', packagingSize: '175', stock: 0 },
  { id: 'P235', name: 'Yoghurt Low Fat Flavoured (VEG)', categoryId: 'CAT010', unitOfMeasure: 'g', packagingSize: '175', stock: 0 },
  { id: 'P236', name: 'Yoghurt Mixed Fruit', categoryId: 'CAT010', unitOfMeasure: 'g', packagingSize: '175', stock: 0 },
  { id: 'P237', name: 'Yoghurt Plain', categoryId: 'CAT010', unitOfMeasure: 'g', packagingSize: '175', stock: 0 },
  { id: 'P238', name: 'Yoghurt Plain Low Fat', categoryId: 'CAT010', unitOfMeasure: 'g', packagingSize: '175', stock: 0 },
  { id: 'P239', name: 'Yoghurt Stewed Fruit', categoryId: 'CAT010', unitOfMeasure: 'g', packagingSize: '175', stock: 0 },
  { id: 'P240', name: 'Yoghurt Strawberry', categoryId: 'CAT010', unitOfMeasure: 'g', packagingSize: '175', stock: 0 },
  { id: 'P241', name: 'Yoghurt Vanilla', categoryId: 'CAT010', unitOfMeasure: 'g', packagingSize: '175', stock: 0 },
  { id: 'P242', name: 'Condensed Milk', categoryId: 'CAT011', unitOfMeasure: 'g', packagingSize: '375', stock: 0 },
  { id: 'P243', name: 'Evaporated Milk', categoryId: 'CAT011', unitOfMeasure: 'g', packagingSize: '375', stock: 0 },
  { id: 'P244', name: 'Ice Cream', categoryId: 'CAT012', unitOfMeasure: 'lt', packagingSize: '5', stock: 0 },
  { id: 'P245', name: 'Butter (K)', categoryId: 'CAT013', unitOfMeasure: 'g', packagingSize: '500', stock: 0 },
  { id: 'P246', name: 'Cream Long Life (K)', categoryId: 'CAT013', unitOfMeasure: 'lt', packagingSize: '1', stock: 0 },
  { id: 'P247', name: 'Margarine Soft Tub (K)', categoryId: 'CAT013', unitOfMeasure: 'g', packagingSize: '500', stock: 0 },
  { id: 'P248', name: 'Portions Butter', categoryId: 'CAT013', unitOfMeasure: 'ea', packagingSize: '', stock: 0 },
  { id: 'P249', name: 'Portions Margarine', categoryId: 'CAT013', unitOfMeasure: '', packagingSize: '294', stock: 0 },
  { id: 'P250', name: 'Sachets Sugar (5G)', categoryId: 'CAT014', unitOfMeasure: 'ea', packagingSize: '1000', stock: 0 },
  { id: 'P251', name: 'Sugar Brown', categoryId: 'CAT014', unitOfMeasure: 'kg', packagingSize: '25', stock: 0 },
  { id: 'P252', name: 'Sugar White', categoryId: 'CAT014', unitOfMeasure: 'kg', packagingSize: '25', stock: 0 },
  { id: 'P253', name: 'Corn Meal (Mealie Meal) (B)', categoryId: 'CAT015', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P254', name: 'Maltabella', categoryId: 'CAT015', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P255', name: 'Rolled Oats', categoryId: 'CAT015', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P256', name: 'Cereal Bran Flakes', categoryId: 'CAT016', unitOfMeasure: 'kg', packagingSize: '500', stock: 0 },
  { id: 'P257', name: 'Cereal Coco Pops', categoryId: 'CAT016', unitOfMeasure: 'g', packagingSize: '500', stock: 0 },
  { id: 'P258', name: 'Cereal Corn Flakes', categoryId: 'CAT016', unitOfMeasure: 'kg', packagingSize: '750', stock: 0 },
  { id: 'P259', name: 'Cereal Muesli Plain', categoryId: 'CAT016', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P260', name: 'Cereal Premixed High Energy', categoryId: 'CAT016', unitOfMeasure: 'g', packagingSize: '500', stock: 0 },
  { id: 'P261', name: 'Cereal Puffed Rice', categoryId: 'CAT016', unitOfMeasure: 'kg', packagingSize: '400', stock: 0 },
  { id: 'P262', name: 'Cereal Whole Grain Cubes', categoryId: 'CAT016', unitOfMeasure: 'g', packagingSize: '900', stock: 0 },
  { id: 'P263', name: 'Corn Cut Frozen', categoryId: 'CAT017', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P264', name: 'Corn Meal (Mielie Meal)', categoryId: 'CAT017', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P265', name: 'Lasagne Sheets (with egg)', categoryId: 'CAT017', unitOfMeasure: 'g', packagingSize: '500', stock: 0 },
  { id: 'P266', name: 'Macaroni', categoryId: 'CAT017', unitOfMeasure: 'g', packagingSize: '500', stock: 0 },
  { id: 'P267', name: 'Macaroni Wholewheat', categoryId: 'CAT017', unitOfMeasure: 'g', packagingSize: '500', stock: 0 },
  { id: 'P268', name: 'Noodle Shells Small', categoryId: 'CAT017', unitOfMeasure: 'g', packagingSize: '500', stock: 0 },
  { id: 'P269', name: 'Noodles Ribbon', categoryId: 'CAT017', unitOfMeasure: 'g', packagingSize: '500', stock: 0 },
  { id: 'P270', name: 'Potato Chips Frozen 10mm', categoryId: 'CAT017', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P271', name: 'Potato Chips Frozen Oven Bake', categoryId: 'CAT017', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P272', name: 'Potato Fresh Pre-Prepared', categoryId: 'CAT017', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P273', name: 'Potato Powder Instant', categoryId: 'CAT017', unitOfMeasure: 'kg', packagingSize: '2', stock: 0 },
  { id: 'P274', name: 'Potatoes Fresh', categoryId: 'CAT017', unitOfMeasure: 'ea', packagingSize: '10', stock: 0 },
  { id: 'P275', name: 'Potatoes Fresh Baby', categoryId: 'CAT017', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P276', name: 'Rice Brown', categoryId: 'CAT017', unitOfMeasure: 'kg', packagingSize: '2', stock: 0 },
  { id: 'P277', name: 'Rice Parboiled White', categoryId: 'CAT017', unitOfMeasure: 'kg', packagingSize: '2', stock: 0 },
  { id: 'P278', name: 'Samp', categoryId: 'CAT017', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P279', name: 'Sorghum Pure Grain (Mabele a Tieng)', categoryId: 'CAT017', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P280', name: 'Spaghetti', categoryId: 'CAT017', unitOfMeasure: 'g', packagingSize: '500', stock: 0 },
  { id: 'P281', name: 'Sweet Potato Fresh', categoryId: 'CAT017', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P282', name: 'Sweet Potato Fresh Frozen', categoryId: 'CAT017', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P283', name: 'Sweet Potato Fresh Pre-prepared', categoryId: 'CAT017', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P284', name: 'Vetkoek Plain Medium', categoryId: 'CAT017', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P285', name: 'Wraps Plain Medium', categoryId: 'CAT017', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P286', name: 'Baby Marrow Fresh', categoryId: 'CAT018', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P287', name: 'Beans Green Frozen', categoryId: 'CAT018', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P288', name: 'Beetroot Fresh', categoryId: 'CAT018', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P289', name: 'Broccoli Fresh Pre-Cut', categoryId: 'CAT018', unitOfMeasure: 'g', packagingSize: '1', stock: 0 },
  { id: 'P290', name: 'Broccoli Frozen', categoryId: 'CAT018', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P291', name: 'Brussel Sprouts Fresh', categoryId: 'CAT018', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P292', name: 'Brussels Sprout Frozen', categoryId: 'CAT018', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P293', name: 'Butternut Fresh', categoryId: 'CAT018', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P294', name: 'Butternut Fresh Pre-Cut', categoryId: 'CAT018', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P295', name: 'Butternut Frozen', categoryId: 'CAT018', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P296', name: 'Cabbage Fresh', categoryId: 'CAT018', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P297', name: 'Cabbage Fresh Pre-Cut', categoryId: 'CAT018', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P298', name: 'Cabbage Red Fresh', categoryId: 'CAT018', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P299', name: 'Cabbage Red Fresh Pre-Cut', categoryId: 'CAT018', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P300', name: 'Carrots Fresh', categoryId: 'CAT018', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P301', name: 'Carrots Fresh Pre-Cut', categoryId: 'CAT018', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P302', name: 'Carrots Frozen', categoryId: 'CAT018', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P303', name: 'Cauliflower Fresh Pre-Cut', categoryId: 'CAT018', unitOfMeasure: 'g', packagingSize: '1', stock: 0 },
  { id: 'P304', name: 'Cauliflower Frozen', categoryId: 'CAT018', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P305', name: 'Corn Fresh', categoryId: 'CAT018', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P306', name: 'Country Mix Frozen', categoryId: 'CAT018', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P307', name: 'Cucumber Fresh', categoryId: 'CAT018', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P308', name: 'Gem Squash Fresh', categoryId: 'CAT018', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P309', name: 'Gem Squash Fresh Pre-Cut', categoryId: 'CAT018', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P310', name: 'Lettuce Fresh', categoryId: 'CAT018', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P311', name: 'Mixed Vegetables Fresh', categoryId: 'CAT018', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P312', name: 'Mushrooms Black Fresh', categoryId: 'CAT018', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P313', name: 'Mushrooms Button Fresh', categoryId: 'CAT018', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P314', name: 'Onions Fresh', categoryId: 'CAT018', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P315', name: 'Onions Fresh Pre-Cut', categoryId: 'CAT018', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P316', name: 'Patti Pans Fresh', categoryId: 'CAT018', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P317', name: 'Peas & Baby Carrot Mix Frozen', categoryId: 'CAT018', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P318', name: 'Peas Fresh', categoryId: 'CAT018', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P319', name: 'Peas Green Frozen', categoryId: 'CAT018', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P320', name: 'Peppers Green Fresh', categoryId: 'CAT018', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P321', name: 'Peppers Green Fresh Pre-Cut', categoryId: 'CAT018', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P322', name: 'Peppers Red Fresh', categoryId: 'CAT018', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P323', name: 'Peppers Red Fresh Pre-Cut', categoryId: 'CAT018', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P324', name: 'Peppers Yellow Fresh', categoryId: 'CAT018', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P325', name: 'Peppers Yellow Fresh Pre-Cut', categoryId: 'CAT018', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P326', name: 'Pumpkin Fresh', categoryId: 'CAT018', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P327', name: 'Pumpkin Fresh Pre-Cut', categoryId: 'CAT018', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P328', name: 'Salad Pre-Made Beetroot', categoryId: 'CAT018', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P329', name: 'Salad Pre-Made Chalaka Salad', categoryId: 'CAT018', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P330', name: 'Salad Pre-Made Coleslaw', categoryId: 'CAT018', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P331', name: 'Salad Pre-Made Potato Salad', categoryId: 'CAT018', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P332', name: 'Spinach Fresh', categoryId: 'CAT018', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P333', name: 'Spinach Fresh Pre-Cut', categoryId: 'CAT018', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P334', name: 'Spinach Frozen', categoryId: 'CAT018', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P335', name: 'Stir Fry Vegetables French Frozen', categoryId: 'CAT018', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P336', name: 'Stir Fry Vegetables Fresh Pre-Cut', categoryId: 'CAT018', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P337', name: 'Stir Fry Vegetables Mushroom Frozen', categoryId: 'CAT018', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P338', name: 'Tomatoes Fresh', categoryId: 'CAT018', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P339', name: 'Apples Fresh', categoryId: 'CAT019', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P340', name: 'Avocados Fresh', categoryId: 'CAT019', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P341', name: 'Bananas Fresh', categoryId: 'CAT019', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P342', name: 'Grapes Fresh', categoryId: 'CAT019', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P343', name: 'Guavas Fresh', categoryId: 'CAT019', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P344', name: 'Lemons Fresh', categoryId: 'CAT019', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P345', name: 'Litchis Fresh', categoryId: 'CAT019', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P346', name: 'Mangoes Fresh', categoryId: 'CAT019', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P347', name: 'Melon Sweet (Spanspek) Fresh', categoryId: 'CAT019', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P348', name: 'Nectarines Fresh', categoryId: 'CAT019', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P349', name: 'Oranges Fresh', categoryId: 'CAT019', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P350', name: 'Papayas Fresh', categoryId: 'CAT019', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P351', name: 'Peaches Fresh', categoryId: 'CAT019', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P352', name: 'Pears Fresh', categoryId: 'CAT019', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P353', name: 'Pineapples Fresh', categoryId: 'CAT019', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P354', name: 'Plums Fresh', categoryId: 'CAT019', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P355', name: 'Tangerines (Nartjies) Fresh', categoryId: 'CAT019', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P356', name: 'Watermelons Fresh', categoryId: 'CAT019', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P357', name: 'Cheese Spreads', categoryId: 'CAT020', unitOfMeasure: 'g', packagingSize: '400', stock: 0 },
  { id: 'P358', name: 'Extract Meat Spread', categoryId: 'CAT020', unitOfMeasure: 'g', packagingSize: '250', stock: 0 },
  { id: 'P359', name: 'Extract Vegetables Spread', categoryId: 'CAT020', unitOfMeasure: 'g', packagingSize: '250', stock: 0 },
  { id: 'P360', name: 'Fish Paste', categoryId: 'CAT020', unitOfMeasure: 'g', packagingSize: '225', stock: 0 },
  { id: 'P361', name: 'Honey', categoryId: 'CAT020', unitOfMeasure: 'g', packagingSize: '500', stock: 0 },
  { id: 'P362', name: 'Jam Apricot Fine', categoryId: 'CAT020', unitOfMeasure: 'g', packagingSize: '900', stock: 0 },
  { id: 'P363', name: 'Jam Mixed Fruit', categoryId: 'CAT020', unitOfMeasure: 'g', packagingSize: '900', stock: 0 },
  { id: 'P364', name: 'Jam Orange Marmalade', categoryId: 'CAT020', unitOfMeasure: 'g', packagingSize: '450', stock: 0 },
  { id: 'P365', name: 'Jam Peach Fine', categoryId: 'CAT020', unitOfMeasure: 'g', packagingSize: '900', stock: 0 },
  { id: 'P366', name: 'Jam Strawberry', categoryId: 'CAT020', unitOfMeasure: 'g', packagingSize: '900', stock: 0 },
  { id: 'P367', name: 'Jam Strawberry Fine', categoryId: 'CAT020', unitOfMeasure: 'g', packagingSize: '900', stock: 0 },
  { id: 'P368', name: 'Peanut Butter', categoryId: 'CAT020', unitOfMeasure: 'g', packagingSize: '400', stock: 0 },
  { id: 'P369', name: 'Portions Extract Vegetables Spread (8G)', categoryId: 'CAT020', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P370', name: 'Portions Honey (20G)', categoryId: 'CAT020', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P371', name: 'Portions Jam Apricot (20G)', categoryId: 'CAT020', unitOfMeasure: 'ea', packagingSize: '200', stock: 0 },
  { id: 'P372', name: 'Portions Jam Assorted (20G)', categoryId: 'CAT020', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P373', name: 'Portions Jam Mixed Fruit (20G)', categoryId: 'CAT020', unitOfMeasure: 'ea', packagingSize: '200', stock: 0 },
  { id: 'P374', name: 'Portions Jam Peach Fine (20G)', categoryId: 'CAT020', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P375', name: 'Portions Jam Plum Fine (20G)', categoryId: 'CAT020', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P376', name: 'Portions Jam Strawberry (20G)', categoryId: 'CAT020', unitOfMeasure: 'ea', packagingSize: '200', stock: 0 },
  { id: 'P377', name: 'Portions Peanut Butter (15G)', categoryId: 'CAT020', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P378', name: 'Syrup', categoryId: 'CAT020', unitOfMeasure: 'g', packagingSize: '500', stock: 0 },
  { id: 'P379', name: 'Assorted Sodas (330Ml)', categoryId: 'CAT021', unitOfMeasure: 'ea', packagingSize: '330', stock: 0 },
  { id: 'P380', name: 'Bags Tea', categoryId: 'CAT021', unitOfMeasure: 'g', packagingSize: '250', stock: 0 },
  { id: 'P381', name: 'Bags Tea Rooibos', categoryId: 'CAT021', unitOfMeasure: 'g', packagingSize: '250', stock: 0 },
  { id: 'P382', name: 'Coffee Granules Instant', categoryId: 'CAT021', unitOfMeasure: 'g', packagingSize: '750', stock: 0 },
  { id: 'P383', name: 'Coffee Roasted Ground', categoryId: 'CAT021', unitOfMeasure: 'g', packagingSize: '750', stock: 0 },
  { id: 'P384', name: 'Hot Chocolate', categoryId: 'CAT021', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P385', name: 'Mageu Banana Flavour (250ml)', categoryId: 'CAT021', unitOfMeasure: 'ml', packagingSize: '500', stock: 0 },
  { id: 'P386', name: 'Mageu Cream Flavour (250ml)', categoryId: 'CAT021', unitOfMeasure: 'ml', packagingSize: '500', stock: 0 },
  { id: 'P387', name: 'Milo', categoryId: 'CAT021', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P388', name: 'Sachets Coffee Granules Instant', categoryId: 'CAT021', unitOfMeasure: 'ea', packagingSize: '200', stock: 0 },
  { id: 'P389', name: 'Sorghum Drink Instant', categoryId: 'CAT021', unitOfMeasure: 'ml', packagingSize: '500', stock: 0 },
  { id: 'P390', name: 'Water Bottled Mineral', categoryId: 'CAT021', unitOfMeasure: 'lt', packagingSize: '5', stock: 0 },
  { id: 'P391', name: 'Assorted Sodas (330Ml)', categoryId: 'CAT022', unitOfMeasure: 'ea', packagingSize: '30', stock: 0 },
  { id: 'P392', name: 'Juice Apple Pure', categoryId: 'CAT022', unitOfMeasure: 'lt', packagingSize: '5', stock: 0 },
  { id: 'P393', name: 'Juice Apple Red', categoryId: 'CAT022', unitOfMeasure: 'lt', packagingSize: '5', stock: 0 },
  { id: 'P394', name: 'Juice Apple White', categoryId: 'CAT022', unitOfMeasure: 'lt', packagingSize: '5', stock: 0 },
  { id: 'P395', name: 'Juice Apricot', categoryId: 'CAT022', unitOfMeasure: 'lt', packagingSize: '5', stock: 0 },
  { id: 'P396', name: 'Juice Fruit Punch Concentrated', categoryId: 'CAT022', unitOfMeasure: 'lt', packagingSize: '5', stock: 0 },
  { id: 'P397', name: 'Juice Granadilla', categoryId: 'CAT022', unitOfMeasure: 'lt', packagingSize: '5', stock: 0 },
  { id: 'P398', name: 'Juice Granadilla Concentrated', categoryId: 'CAT022', unitOfMeasure: 'lt', packagingSize: '5', stock: 0 },
  { id: 'P399', name: 'Juice Guava Concentrated', categoryId: 'CAT022', unitOfMeasure: 'lt', packagingSize: '5', stock: 0 },
  { id: 'P400', name: 'Juice Litchi Concentrated', categoryId: 'CAT022', unitOfMeasure: 'lt', packagingSize: '5', stock: 0 },
  { id: 'P401', name: 'Juice Mango Concentrated', categoryId: 'CAT022', unitOfMeasure: 'lt', packagingSize: '5', stock: 0 },
  { id: 'P402', name: 'Juice Naartjie Concentrated', categoryId: 'CAT022', unitOfMeasure: 'lt', packagingSize: '5', stock: 0 },
  { id: 'P403', name: 'Juice Orange And Naartjie', categoryId: 'CAT022', unitOfMeasure: 'lt', packagingSize: '5', stock: 0 },
  { id: 'P404', name: 'Juice Orange Apple Or Grape', categoryId: 'CAT022', unitOfMeasure: 'lt', packagingSize: '5', stock: 0 },
  { id: 'P405', name: 'Juice Orange Concentrated', categoryId: 'CAT022', unitOfMeasure: 'lt', packagingSize: '5', stock: 0 },
  { id: 'P406', name: 'Juice Peach Concentrated', categoryId: 'CAT022', unitOfMeasure: 'lt', packagingSize: '5', stock: 0 },
  { id: 'P407', name: 'Juice Pre-mix all flavours', categoryId: 'CAT022', unitOfMeasure: 'ml', packagingSize: '250', stock: 0 },
  { id: 'P408', name: 'Juice Tomato Cocktail (200Ml)', categoryId: 'CAT022', unitOfMeasure: 'lt', packagingSize: '5', stock: 0 },
  { id: 'P409', name: 'Atchar Mango(DR)', categoryId: 'CAT023', unitOfMeasure: 'g', packagingSize: '400', stock: 0 },
  { id: 'P410', name: 'Atchar Vegetables (DR)', categoryId: 'CAT023', unitOfMeasure: 'g', packagingSize: '400', stock: 0 },
  { id: 'P411', name: 'BBQ Sauce (DR)', categoryId: 'CAT023', unitOfMeasure: 'lt', packagingSize: '375', stock: 0 },
  { id: 'P412', name: 'Butter Portions (DR)', categoryId: 'CAT023', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P413', name: 'Capers (DR)', categoryId: 'CAT023', unitOfMeasure: 'g', packagingSize: '400', stock: 0 },
  { id: 'P414', name: 'Chakalaka (DR)', categoryId: 'CAT023', unitOfMeasure: 'g', packagingSize: '410', stock: 0 },
  { id: 'P415', name: 'Chilli Sauce (DR)', categoryId: 'CAT023', unitOfMeasure: 'ml', packagingSize: '750', stock: 0 },
  { id: 'P416', name: 'Chutney Mild (DR)', categoryId: 'CAT023', unitOfMeasure: 'lt', packagingSize: '750', stock: 0 },
  { id: 'P417', name: 'Gherkins (DR)', categoryId: 'CAT023', unitOfMeasure: 'g', packagingSize: '375', stock: 0 },
  { id: 'P418', name: 'Jam Portions Assorted (DR)', categoryId: 'CAT023', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P419', name: 'Margarine Portions  (DR)', categoryId: 'CAT023', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P420', name: 'Margarine Soft Tub (DR)', categoryId: 'CAT023', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P421', name: 'Mixed Pickles (DR)', categoryId: 'CAT023', unitOfMeasure: 'g', packagingSize: '400', stock: 0 },
  { id: 'P422', name: 'Mustard Prepared Mild (DR)', categoryId: 'CAT023', unitOfMeasure: 'ea', packagingSize: '165', stock: 0 },
  { id: 'P423', name: 'Nandos Sauce (DR)', categoryId: 'CAT023', unitOfMeasure: 'ml', packagingSize: '250', stock: 0 },
  { id: 'P424', name: 'Pepper Black Ground (DR)', categoryId: 'CAT023', unitOfMeasure: 'g', packagingSize: '800', stock: 0 },
  { id: 'P425', name: 'Pepper Black Ground (DR)', categoryId: 'CAT023', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P426', name: 'Pepper Black Sachets (DR)', categoryId: 'CAT023', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P427', name: 'Pepper White Ground (DR)', categoryId: 'CAT023', unitOfMeasure: 'g', packagingSize: '100', stock: 0 },
  { id: 'P428', name: 'Pepper White Ground (DR)', categoryId: 'CAT023', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P429', name: 'Pepper White Sachets (DR)', categoryId: 'CAT023', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P430', name: 'Piccalilli (DR)', categoryId: 'CAT023', unitOfMeasure: 'g', packagingSize: '400', stock: 0 },
  { id: 'P431', name: 'Sachets Chutney Mild (8G)', categoryId: 'CAT023', unitOfMeasure: 'ea', packagingSize: '400', stock: 0 },
  { id: 'P432', name: 'Sachets Mustard Prepared (8G)', categoryId: 'CAT023', unitOfMeasure: 'ea', packagingSize: '400', stock: 0 },
  { id: 'P433', name: 'Sachets Pepper (5G)', categoryId: 'CAT023', unitOfMeasure: 'ea', packagingSize: '1000', stock: 0 },
  { id: 'P434', name: 'Sachets Salt (5G)', categoryId: 'CAT023', unitOfMeasure: 'ea', packagingSize: '1000', stock: 0 },
  { id: 'P435', name: 'Sachets Tomato Sauce (8G)', categoryId: 'CAT023', unitOfMeasure: 'g', packagingSize: '200', stock: 0 },
  { id: 'P436', name: 'Sachets Worcester Sauce (8G)', categoryId: 'CAT023', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P437', name: 'Salad Dressing (DR)', categoryId: 'CAT023', unitOfMeasure: 'ml', packagingSize: '340', stock: 0 },
  { id: 'P438', name: 'Salad Dressing Lite (DR)', categoryId: 'CAT023', unitOfMeasure: 'lt', packagingSize: '1', stock: 0 },
  { id: 'P439', name: 'Salt Table (DR)', categoryId: 'CAT023', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P440', name: 'Salt Table (DR)', categoryId: 'CAT023', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P441', name: 'Salt Table Sachets (DR)', categoryId: 'CAT023', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P442', name: 'Tomato Sauce (DR)', categoryId: 'CAT023', unitOfMeasure: 'lt', packagingSize: '750', stock: 0 },
  { id: 'P443', name: 'Worcester Sauce (DR)', categoryId: 'CAT023', unitOfMeasure: 'lt', packagingSize: '250', stock: 0 },
  { id: 'P444', name: 'Atchar Mango (K)', categoryId: 'CAT024', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P445', name: 'Atchar Vegetables (K)', categoryId: 'CAT024', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P446', name: 'Baking Powder (K)', categoryId: 'CAT024', unitOfMeasure: 'g', packagingSize: '500', stock: 0 },
  { id: 'P447', name: 'BBQ Sauce (K)', categoryId: 'CAT024', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P448', name: 'Beans Butter Dry (K)', categoryId: 'CAT024', unitOfMeasure: 'g', packagingSize: '500', stock: 0 },
  { id: 'P449', name: 'Bicarbonate Of Soda (K)', categoryId: 'CAT024', unitOfMeasure: 'kg', packagingSize: '500', stock: 0 },
  { id: 'P450', name: 'Cake Flour (K)', categoryId: 'CAT024', unitOfMeasure: 'kg', packagingSize: '10', stock: 0 },
  { id: 'P451', name: 'Capers (K)', categoryId: 'CAT024', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P452', name: 'Chakalaka (K)', categoryId: 'CAT024', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P453', name: 'Chilli Sauce (K)', categoryId: 'CAT024', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P454', name: 'Chutney Mild (K)', categoryId: 'CAT024', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P455', name: 'Cocoa Powder (K)', categoryId: 'CAT024', unitOfMeasure: 'g', packagingSize: '100', stock: 0 },
  { id: 'P456', name: 'Coconut Prepared (K)', categoryId: 'CAT024', unitOfMeasure: 'kg', packagingSize: '100', stock: 0 },
  { id: 'P457', name: 'Cooking Oil Canola (K)', categoryId: 'CAT024', unitOfMeasure: 'lt', packagingSize: '20', stock: 0 },
  { id: 'P458', name: 'Cooking Oil Sunflower (K)', categoryId: 'CAT024', unitOfMeasure: 'lt', packagingSize: '750', stock: 0 },
  { id: 'P459', name: 'Corn Flour (K)', categoryId: 'CAT024', unitOfMeasure: 'g', packagingSize: '500', stock: 0 },
  { id: 'P460', name: 'Custard Powder(K)', categoryId: 'CAT024', unitOfMeasure: 'kg', packagingSize: '500', stock: 0 },
  { id: 'P461', name: 'Dates (K)', categoryId: 'CAT024', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P462', name: 'Dried Apricots (K)', categoryId: 'CAT024', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P463', name: 'Dried Currents (K)', categoryId: 'CAT024', unitOfMeasure: 'g', packagingSize: '500', stock: 0 },
  { id: 'P464', name: 'Dried Fruit Salad (K)', categoryId: 'CAT024', unitOfMeasure: 'g', packagingSize: '410', stock: 0 },
  { id: 'P465', name: 'Dried Peaches (K)', categoryId: 'CAT024', unitOfMeasure: 'g', packagingSize: '250', stock: 0 },
  { id: 'P466', name: 'Dried Prunes (K)', categoryId: 'CAT024', unitOfMeasure: 'g', packagingSize: '500', stock: 0 },
  { id: 'P467', name: 'Dried Sultanas (K)', categoryId: 'CAT024', unitOfMeasure: 'g', packagingSize: '250', stock: 0 },
  { id: 'P468', name: 'Eggs Large Fresh (K)', categoryId: 'CAT024', unitOfMeasure: 'ea', packagingSize: '30', stock: 0 },
  { id: 'P469', name: 'Essence Vanilla (K)', categoryId: 'CAT024', unitOfMeasure: 'lt', packagingSize: '1', stock: 0 },
  { id: 'P470', name: 'Gherkins (K)', categoryId: 'CAT024', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P471', name: 'Gravy Mix Beef Bisto (K)', categoryId: 'CAT024', unitOfMeasure: 'kg', packagingSize: '250', stock: 0 },
  { id: 'P472', name: 'Gravy Powder (K)', categoryId: 'CAT024', unitOfMeasure: 'kg', packagingSize: '2.5', stock: 0 },
  { id: 'P473', name: 'Lemon Juice (K)', categoryId: 'CAT024', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P474', name: 'Lentils Brown (K)', categoryId: 'CAT024', unitOfMeasure: 'g', packagingSize: '500', stock: 0 },
  { id: 'P475', name: 'Lentils Dry (K)', categoryId: 'CAT024', unitOfMeasure: 'g', packagingSize: '500', stock: 0 },
  { id: 'P476', name: 'Margerine Bricks', categoryId: 'CAT024', unitOfMeasure: 'g', packagingSize: '500', stock: 0 },
  { id: 'P477', name: 'Mayonnaise (K)', categoryId: 'CAT024', unitOfMeasure: 'lt', packagingSize: '20', stock: 0 },
  { id: 'P478', name: 'Mixed Pickles (K)', categoryId: 'CAT024', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P479', name: 'Mustard Prepared Mild (K)', categoryId: 'CAT024', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P480', name: 'Nandos Sauce (K)', categoryId: 'CAT024', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P481', name: 'Pepper Black Ground (K)', categoryId: 'CAT024', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P482', name: 'Pepper White Ground (K)', categoryId: 'CAT024', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P483', name: 'Piccalilli (K)', categoryId: 'CAT024', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P484', name: 'Raisins (K)', categoryId: 'CAT024', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P485', name: 'Salad Dressing (K)', categoryId: 'CAT024', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P486', name: 'Salad Dressing Lite (K)', categoryId: 'CAT024', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P487', name: 'Salt Table (K)', categoryId: 'CAT024', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P488', name: 'Soya Sauce (K)', categoryId: 'CAT024', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P489', name: 'Split Peas (K)', categoryId: 'CAT024', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P490', name: 'Stock Cubes Beef (K)', categoryId: 'CAT024', unitOfMeasure: 'ea', packagingSize: '12', stock: 0 },
  { id: 'P491', name: 'Stock Cubes Chicken (K)', categoryId: 'CAT024', unitOfMeasure: 'ea', packagingSize: '12', stock: 0 },
  { id: 'P492', name: 'Stock Powder Beef (K)', categoryId: 'CAT024', unitOfMeasure: 'ea', packagingSize: '12', stock: 0 },
  { id: 'P493', name: 'Stock Powder Chicken (K)', categoryId: 'CAT024', unitOfMeasure: 'ea', packagingSize: '12', stock: 0 },
  { id: 'P494', name: 'Stock Powder Vegetable (K)', categoryId: 'CAT024', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P495', name: 'Sugar Beans (K)', categoryId: 'CAT024', unitOfMeasure: 'g', packagingSize: '500', stock: 0 },
  { id: 'P496', name: 'Tinned Apricots (K)', categoryId: 'CAT024', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P497', name: 'Tinned Mixed Fruit Salad (K)', categoryId: 'CAT024', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P498', name: 'Tinned Peaches (K)', categoryId: 'CAT024', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P499', name: 'Tinned Pears (K)', categoryId: 'CAT024', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P500', name: 'Tinned Pineapple (K)', categoryId: 'CAT024', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P501', name: 'Tomato Paste (K)', categoryId: 'CAT024', unitOfMeasure: 'g', packagingSize: '410', stock: 0 },
  { id: 'P502', name: 'Tomato Sauce (K)', categoryId: 'CAT024', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P503', name: 'Vinegar (K)', categoryId: 'CAT024', unitOfMeasure: 'ml', packagingSize: '750', stock: 0 },
  { id: 'P504', name: 'Vinegar Brown (K)', categoryId: 'CAT024', unitOfMeasure: 'lt', packagingSize: '5', stock: 0 },
  { id: 'P505', name: 'Worcester Sauce (K)', categoryId: 'CAT024', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P506', name: 'Yeast Instant Sachets (K)', categoryId: 'CAT024', unitOfMeasure: 'ea', packagingSize: '24', stock: 0 },
  { id: 'P507', name: 'Aromat Seasoning Salt', categoryId: 'CAT025', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P508', name: 'Barbeque Spice', categoryId: 'CAT025', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P509', name: 'Bay Leaves Whole', categoryId: 'CAT025', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P510', name: 'Breyani Mix', categoryId: 'CAT025', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P511', name: 'Celery Fresh', categoryId: 'CAT025', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P512', name: 'Chicken Spice', categoryId: 'CAT025', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P513', name: 'Cinnamon Ground', categoryId: 'CAT025', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P514', name: 'Cloves Ground', categoryId: 'CAT025', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P515', name: 'Coriander Fresh', categoryId: 'CAT025', unitOfMeasure: 'g', packagingSize: '1', stock: 0 },
  { id: 'P516', name: 'Coriander Powder', categoryId: 'CAT025', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P517', name: 'Coriander Whole', categoryId: 'CAT025', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P518', name: 'Cumin Powder', categoryId: 'CAT025', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P519', name: 'Cumin Seeds', categoryId: 'CAT025', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P520', name: 'Curry Powder Blend Ground', categoryId: 'CAT025', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P521', name: 'Dried Parsley', categoryId: 'CAT025', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P522', name: 'Fish Spice', categoryId: 'CAT025', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P523', name: 'Garlic Dry Flakes', categoryId: 'CAT025', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P524', name: 'Garlic Fresh', categoryId: 'CAT025', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P525', name: 'Ginger Fresh', categoryId: 'CAT025', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P526', name: 'Mixed Herbs', categoryId: 'CAT025', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P527', name: 'Mustard Powder Ground', categoryId: 'CAT025', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P528', name: 'Mustard Seeds Black', categoryId: 'CAT025', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P529', name: 'Nutmeg Ground', categoryId: 'CAT025', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P530', name: 'Paprika Ground', categoryId: 'CAT025', unitOfMeasure: 'g', packagingSize: '700', stock: 0 },
  { id: 'P531', name: 'Parsley Fresh', categoryId: 'CAT025', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P532', name: 'Pepper Cayenne Ground', categoryId: 'CAT025', unitOfMeasure: 'g', packagingSize: '800', stock: 0 },
  { id: 'P533', name: 'Pepper Corns Black', categoryId: 'CAT025', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P534', name: 'Peri Peri Ground', categoryId: 'CAT025', unitOfMeasure: 'g', packagingSize: '100', stock: 0 },
  { id: 'P535', name: 'Potato Spice', categoryId: 'CAT025', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P536', name: 'Rice Spice', categoryId: 'CAT025', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P537', name: 'Rosemary Fresh', categoryId: 'CAT025', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P538', name: 'Spring Onions Fresh', categoryId: 'CAT025', unitOfMeasure: 'g', packagingSize: '1', stock: 0 },
  { id: 'P539', name: 'Steak and Chop', categoryId: 'CAT025', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P540', name: 'Sweet Basil Dried', categoryId: 'CAT025', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P541', name: 'Sweet Basil Fresh', categoryId: 'CAT025', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P542', name: 'Tamarind', categoryId: 'CAT025', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P543', name: 'Thyme Ground', categoryId: 'CAT025', unitOfMeasure: 'g', packagingSize: '1', stock: 0 },
  { id: 'P544', name: 'Turmeric Ground', categoryId: 'CAT025', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P545', name: 'Vegetable Spice', categoryId: 'CAT025', unitOfMeasure: 'kg', packagingSize: '1', stock: 0 },
  { id: 'P546', name: 'Jelly Greengage', categoryId: 'CAT026', unitOfMeasure: 'kg', packagingSize: '4', stock: 0 },
  { id: 'P547', name: 'Jelly Lemon', categoryId: 'CAT026', unitOfMeasure: 'kg', packagingSize: '4', stock: 0 },
  { id: 'P548', name: 'Jelly Orange', categoryId: 'CAT026', unitOfMeasure: 'kg', packagingSize: '4', stock: 0 },
  { id: 'P549', name: 'Jelly Raspberry', categoryId: 'CAT026', unitOfMeasure: 'kg', packagingSize: '4', stock: 0 },
  { id: 'P550', name: 'Jelly Strawberry', categoryId: 'CAT026', unitOfMeasure: 'kg', packagingSize: '4', stock: 0 },
  { id: 'P551', name: 'Pre-Prepared Cheesecake', categoryId: 'CAT026', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P552', name: 'Pre-Prepared Chocolate Cake', categoryId: 'CAT026', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P553', name: 'Pre-Prepared Fridge Tart', categoryId: 'CAT026', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P554', name: 'Pre-Prepared Fruit Salad', categoryId: 'CAT026', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P555', name: 'Pre-Prepared Malva Pudding', categoryId: 'CAT026', unitOfMeasure: 'ea', packagingSize: '1', stock: 0 },
  { id: 'P556', name: 'Pre-Prepared Milk Tart', categoryId: 'CAT026', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P557', name: 'Soup Brown Onion', categoryId: 'CAT027', unitOfMeasure: 'kg', packagingSize: '1.6', stock: 0 },
  { id: 'P558', name: 'Soup Chicken', categoryId: 'CAT027', unitOfMeasure: 'kg', packagingSize: '1.6', stock: 0 },
  { id: 'P559', name: 'Soup Minestrone', categoryId: 'CAT027', unitOfMeasure: 'kg', packagingSize: '1.6', stock: 0 },
  { id: 'P560', name: 'Soup Mushroom', categoryId: 'CAT027', unitOfMeasure: 'kg', packagingSize: '1.6', stock: 0 },
  { id: 'P561', name: 'Soup Oxtail', categoryId: 'CAT027', unitOfMeasure: 'kg', packagingSize: '1.6', stock: 0 },
  { id: 'P562', name: 'Soup Thick Vegetable', categoryId: 'CAT027', unitOfMeasure: 'kg', packagingSize: '1.6', stock: 0 },
  { id: 'P563', name: 'Soup Tomato', categoryId: 'CAT027', unitOfMeasure: 'kg', packagingSize: '1.6', stock: 0 },
  { id: 'P564', name: 'Soup White Onion', categoryId: 'CAT027', unitOfMeasure: 'kg', packagingSize: '1.6', stock: 0 },
  { id: 'P565', name: 'Dessert Sauce Pre-made B Strawberry Sauce', categoryId: 'CAT028', unitOfMeasure: 'lt', packagingSize: '', stock: 0 },
  { id: 'P566', name: 'Dessert Sauce Pre-made Mango Sauce', categoryId: 'CAT028', unitOfMeasure: 'lt', packagingSize: '', stock: 0 },
  { id: 'P567', name: '100', categoryId: 'CAT029', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P568', name: '200', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P569', name: '201', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P570', name: '202', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P571', name: '203', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P572', name: '204', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P573', name: '205', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P574', name: '206', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P575', name: '207', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P576', name: '208', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P577', name: '209', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P578', name: '210', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P579', name: '211', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P580', name: '212', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P581', name: '213', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P582', name: '214', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P583', name: '215', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P584', name: '216', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P585', name: '217', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P586', name: '218', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P587', name: '219', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P588', name: '220', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P589', name: '221', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P590', name: '222', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P591', name: '223', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P592', name: '224', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P593', name: '225', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P594', name: '226', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P595', name: '227', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P596', name: '228', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P597', name: '229', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P598', name: '230', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P599', name: '231', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P600', name: '232', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P601', name: '233', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P602', name: 'Assorted Simba Chips (36g)', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P603', name: 'Charcoal', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P604', name: 'Chocolate Bar One', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P605', name: 'Chocolate Crunchie', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P606', name: 'Chocolate Kit Kat', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P607', name: 'Chocolate Lunch Bar', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P608', name: 'Chocolate PS', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P609', name: 'Chocolate Smarties', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P610', name: 'Chocolate Snickers', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P611', name: 'Chocolate Tex', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P612', name: 'Chocolate TV Bar', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P613', name: 'Chocolate Twix', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P614', name: 'Crumbed Onion Rings', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P615', name: 'Fire Lighters', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P616', name: 'Nuts Salted Peanuts', categoryId: 'CAT030', unitOfMeasure: 'g', packagingSize: '60', stock: 0 },
  { id: 'P617', name: 'Nuts Salted Peanuts & Raisins', categoryId: 'CAT030', unitOfMeasure: 'g', packagingSize: '60', stock: 0 },
  { id: 'P618', name: 'Sweets Jelly Babies', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P619', name: 'Sweets Jelly Tots', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P620', name: 'Sweets Mentos', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P621', name: 'Sweets Rascalls', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P622', name: 'Sweets Skittles', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P623', name: 'Sweets Wine Gum Rolls', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P624', name: '234', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P625', name: '234', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P626', name: '234', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P627', name: '234', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P628', name: '234', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P629', name: '234', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P630', name: '234', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P631', name: '234', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P632', name: '234', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P633', name: '234', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P634', name: '234', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P635', name: '234', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P636', name: '234', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P637', name: '234', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P638', name: '234', categoryId: 'CAT030', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P639', name: '300', categoryId: 'CAT031', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P640', name: '301', categoryId: 'CAT031', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P641', name: '302', categoryId: 'CAT031', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P642', name: '303', categoryId: 'CAT031', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P643', name: '304', categoryId: 'CAT031', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P644', name: '305', categoryId: 'CAT031', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P645', name: '306', categoryId: 'CAT031', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P646', name: '307', categoryId: 'CAT031', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P647', name: '308', categoryId: 'CAT031', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P648', name: '309', categoryId: 'CAT031', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P649', name: '310', categoryId: 'CAT031', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P650', name: '311', categoryId: 'CAT031', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P651', name: '312', categoryId: 'CAT031', unitOfMeasure: '', packagingSize: '', stock: 0 },
  { id: 'P652', name: '313', categoryId: 'CAT031', unitOfMeasure: '', packagingSize: '', stock: 0 },
];

export const dishes: Dish[] = [
  // Dishes data removed as it was linked to old ingredients
];

export const orders: Order[] = [
  // Orders data removed as it's not relevant to the new data
];
